/*
 * @Date: 1985-10-26 16:15:00
 * @LastEditors: M.re c1029mq@qq.com
 * @LastEditTime: 2022-09-01 11:29:15
 * @FilePath: /my-app/pages/privacy/index.js
 */
import Head from 'next/head';
import styles from './index.module.scss';
import {useRouter} from 'next/router';
import Layout from '@/components/layout/layout';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';
export async function getStaticProps (context) {
  const res = await fetch (`http://localhost:3001/api/test`);
  let info = await res.json ();
  return {
    props: {...info, ...(await serverSideTranslations(context.locale, ['common']))}, // will be passed to the page component as props
  };
}
export default function Posts (props) {
  const router = useRouter ();
  const {t} = useTranslation('common')
  console.log (props, 'privacy');
  return (
    <div className={styles.container}>
      <Head>
        <title>post</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
    

        <Layout t={t}>
        <main className={styles.main_content}>
        <button onClick={() => router.push('/')}>
      Click here to read more
    </button>
          {process.env.NEXT_PUBLIC_ENV}
          {process.env.NEXT_PUBLIC_ENV_TEST}
          </main>
        </Layout>
      
    </div>
  );
}
