import Document, { Html, Head, Main, NextScript } from 'next/document';

export default class MyDocument extends Document {
  constructor(props) {
    super(props);
  }
 meta = [
    {
      name: 'description',
      content: 'Generated by create next app',
    },
    // {
    //   name: 'viewport',
    //   content:
    //     'width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no',
    // },
  ];
  render() {
    return (
      <Html lang="en">
        <Head>
          {this.meta.map((item) => {
            return (
              <meta name={item.name} content={item.content} key={item.name} />
            );
          })}
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
