/*
 * @Date: 2022-09-01 17:31:00
 * @LastEditors: M.re c1029mq@qq.com
 * @LastEditTime: 2022-09-02 17:18:50
 * @FilePath: /uuspy-website-node/pages/_document.js
 */
import Document, { Html, Head, Main, NextScript } from 'next/document';
export async function getStaticProps (context) {
  return {
    props: {locale: context.locale}, // will be passed to the page component as props
  };
}
export default class MyDocument extends Document {
  constructor(props) {
    super(props);
    this.state = {
      ...props
    };
  }
 meta = [
    {
      name: 'description',
      content: 'Generated by create next app',
    },
    // {
    //   name: 'viewport',
    //   content:
    //     'width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no',
    // },
  ];

  render() {
  console.log('..props',this.props)
    const { locale } = this.state
    return (
      <Html lang={locale}>
        <Head>
          {this.meta.map((item) => {
            return (
              <meta name={item.name} content={item.content} key={item.name} />
            );
          })}
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
